In [1]:
## Dependencies and setup
import pandas as pd

In [2]:
## Load data files
pesticide_kiwi = "../../1_Extract/USDA-Pesticide_Use/pesticide_kiwi.csv"

In [3]:
## Read data and store into df
pesticide_kiwi = pd.read_csv(pesticide_kiwi)
pesticide_kiwi

,Program,Year,Period,Week Ending,Geo Level,State,State ANSI,Ag District,Ag District Code,County,...,"KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB - <b>CV (%)</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB / ACRE / APPLICATION, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB / ACRE / APPLICATION, AVG - <b>CV (%)</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB / ACRE / YEAR, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB / ACRE / YEAR, AVG - <b>CV (%)</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN NUMBER, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN NUMBER, AVG - <b>CV (%)</b>","KIWIFRUIT, BEARING - TREATED, MEASURED IN PCT OF AREA BEARING, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - TREATED, MEASURED IN PCT OF AREA BEARING, AVG - <b>CV (%)</b>"
0,SURVEY,2019,YEAR,NaN,REGION : MULTI-STATE,NaN,NaN,NaN,NaN,NaN,...,(NA),NaN,(NA),NaN,(NA),NaN,(D),NaN,(D),NaN
1,SURVEY,2019,YEAR,NaN,REGION : MULTI-STATE,NaN,NaN,NaN,NaN,NaN,...,(D),NaN,(D),NaN,(D),NaN,(D),NaN,(D),NaN
2,SURVEY,2019,YEAR,NaN,REGION : MULTI-STATE,NaN,NaN,NaN,NaN,NaN,...,(D),NaN,(D),NaN,(D),NaN,(D),NaN,(D),NaN
3,SURVEY,2019,YEAR,NaN,REGION : MULTI-STATE,NaN,NaN,NaN,NaN,NaN,...,(D),NaN,(D),NaN,(D),NaN,(D),NaN,(D),NaN
4,SURVEY,2019,YEAR,NaN,REGION : MULTI-STATE,NaN,NaN,NaN,NaN,NaN,...,"1,300",NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,SURVEY,1993,YEAR,NaN,STATE,CALIFORNIA,6.0,NaN,NaN,NaN,...,"3,500",NaN,0.63,NaN,0.97,NaN,1.5,NaN,53,NaN
258,SURVEY,1993,YEAR,NaN,STATE,CALIFORNIA,6.0,NaN,NaN,NaN,...,"3,400",NaN,2.99,NaN,2.99,NaN,1,NaN,17,NaN
259,SURVEY,1993,YEAR,NaN,STATE,CALIFORNIA,6.0,NaN,NaN,NaN,...,"1,100",NaN,1,NaN,1.19,NaN,1.2,NaN,13,NaN
260,SURVEY,1993,YEAR,NaN,STATE,CALIFORNIA,6.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,NaN
261,SURVEY,1993,YEAR,NaN,STATE,CALIFORNIA,6.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN

In [4]:
## Drop erroneous columns
remove = [0, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 19, 21, 23, 25, 27]
pesticide_kiwi.drop(pesticide_kiwi.iloc[:, remove], axis = 1, inplace = True)

pesticide_kiwi.head()

,Year,State,Domain,Domain Category,"KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB / ACRE / APPLICATION, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN LB / ACRE / YEAR, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - APPLICATIONS, MEASURED IN NUMBER, AVG - <b>VALUE</b>","KIWIFRUIT, BEARING - TREATED, MEASURED IN PCT OF AREA BEARING, AVG - <b>VALUE</b>"
0,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",(NA),(NA),(NA),(D),(D)
1,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",(D),(D),(D),(D),(D)
2,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",(D),(D),(D),(D),(D)
3,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",(D),(D),(D),(D),(D)
4,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36

In [5]:
## Rename columns
pesticide_kiwi.columns = ["year", "state", "chemical_type", "chemical_name", "chem_app(lbs)", "lb/acre/app(avg)", "lb/acre/yr(avg)", "num_app(avg)", "pct_area_treated(avg)"]

pesticide_kiwi.head()

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
0,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",(NA),(NA),(NA),(D),(D)
1,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",(D),(D),(D),(D),(D)
2,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",(D),(D),(D),(D),(D)
3,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",(D),(D),(D),(D),(D)
4,2019,NaN,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36

In [6]:
## Drop blank rows
# pesticide_kiwi = pesticide_kiwi.dropna()

In [7]:
## Rename empty "state" cells
pesticide_kiwi["state"] = pesticide_kiwi["state"].fillna("Other States")
pesticide_kiwi.head()

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
0,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",(NA),(NA),(NA),(D),(D)
1,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",(D),(D),(D),(D),(D)
2,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",(D),(D),(D),(D),(D)
3,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",(D),(D),(D),(D),(D)
4,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36

In [8]:
## (D) defined as:
## Withheld to avoid disclosing data for individual farms.

## (NA) defined as:
## Not available. Rate and total applied data items are not available in the standard units for biological active ingredients. Biological active ingredients often consist of microscopic organisms – the concentrations of which are often reported in parts per million, cfu/g (colony forming units/gram) or viable spores/gram.

## Replace (D) and (NA) values with None
pesticide_kiwi = pesticide_kiwi.replace({" (NA)": None})
pesticide_kiwi = pesticide_kiwi.replace({" (D)": None})
pesticide_kiwi

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
0,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",None,None,None,None,None
1,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",None,None,None,None,None
2,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",None,None,None,None,None
3,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",None,None,None,None,None
4,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36
...,...,...,...,...,...,...,...,...,...
257,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLYPHOSATE = 417300)","3,500",0.63,0.97,1.5,53
258,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (ORYZALIN = 104201)","3,400",2.99,2.99,1,17
259,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (OXYFLUORFEN = 111601)","1,100",1,1.19,1.2,13
260,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (TOTAL)",NaN,NaN,NaN,NaN,63
261,1993,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (TOTAL)",NaN,NaN,NaN,NaN,11

In [9]:
## (Z) defines as:
## Less than half of rounding unit for data item shown
## Replace (Z) with 0
pesticide_kiwi = pesticide_kiwi.replace({" (Z)": 0})
pesticide_kiwi

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
0,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",None,None,None,None,None
1,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",None,None,None,None,None
2,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",None,None,None,None,None
3,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",None,None,None,None,None
4,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36
...,...,...,...,...,...,...,...,...,...
257,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLYPHOSATE = 417300)","3,500",0.63,0.97,1.5,53
258,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (ORYZALIN = 104201)","3,400",2.99,2.99,1,17
259,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (OXYFLUORFEN = 111601)","1,100",1,1.19,1.2,13
260,1993,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (TOTAL)",NaN,NaN,NaN,NaN,63
261,1993,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (TOTAL)",NaN,NaN,NaN,NaN,11

In [10]:
## Find all 2019 data in col["year"]
pesticide_kiwi = pesticide_kiwi[pesticide_kiwi["year"] == 2019]
pesticide_kiwi

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
0,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",None,None,None,None,None
1,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",None,None,None,None,None
2,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",None,None,None,None,None
3,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",None,None,None,None,None
4,2019,Other States,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36
5,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLUFOSINATE-AMMONIUM = 1...",None,None,None,None,None
6,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLYPHOSATE ISO. SALT = 1...",100,0.393,0.469,1.2,6
7,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLYPHOSATE POT. SALT = 1...","4,200",2.003,7.96,4,13
8,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (ORYZALIN = 104201)","10,100",3.783,7.187,1.9,36
9,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (OXYFLUORFEN = 111601)","3,500",1.382,2.425,1.8,37
10,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (PARAQUAT = 61601)",300,1.01,1.978,2,4
11,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (PYRAFLUFEN-ETHYL = 30090)",None,None,None,None,None
12,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (SAFLUFENACIL = 118203)",None,None,None,None,None
13,2019,Other States,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (TOTAL)","18,300",NaN,NaN,NaN,53
14,2019,Other States,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (BT KURSTAKI ABTS-351 =...",None,None,None,None,None
15,2019,Other States,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (CHLORANTRANILIPROLE = ...",None,None,None,None,None
16,2019,Other States,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (CRYOLITE = 75101)",None,None,None,None,None
17,2019,Other States,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (ESFENVALERATE = 109303)",None,None,None,None,None
18,2019,Other States,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (PYRIPROXYFEN = 129032)",100,0.103,0.121,1.2,17
19,2019,Other States,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (TOTAL)","1,500",NaN,NaN,NaN,24
20,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (BT KURSTAKI SA-12 = 6518)",None,None,None,None,None
21,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (CYANAMID = 14002)","80,500",17.165,47.061,2.7,44
22,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (DICHLOROPROPENE = 29001)",None,None,None,None,None
23,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (FORCHLORFENURON = 128819)","1,400",0.356,0.829,2.3,45
24,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (MINERAL OIL = 63502)",None,None,None,None,None
25,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (STRYCHNINE = 76901)",None,None,None,None,None
26,2019,Other States,"CHEMICAL, OTHER","CHEMICAL, OTHER: (TOTAL)","93,100",NaN,NaN,NaN,53
27,2019,CALIFORNIA,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (BACILLUS AMYLOLIQUEFACIE...",None,None,None,None,None
28,2019,CALIFORNIA,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (COPPER HYDROXIDE = 23401)",None,None,None,None,None
29,2019,CALIFORNIA,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (CYPRODINIL = 288202)",None,None,None,None,None
30,2019,CALIFORNIA,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (MEFENOXAM = 113502)",None,None,None,None,None
31,2019,CALIFORNIA,"CHEMICAL, FUNGICIDE","CHEMICAL, FUNGICIDE: (TOTAL)","1,300",NaN,NaN,NaN,36
32,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLUFOSINATE-AMMONIUM = 1...",None,None,None,None,None
33,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLYPHOSATE ISO. SALT = 1...",100,0.393,0.469,1.2,6
34,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (GLYPHOSATE POT. SALT = 1...","4,200",2.003,7.96,4,13
35,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (ORYZALIN = 104201)","10,100",3.783,7.187,1.9,36
36,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (OXYFLUORFEN = 111601)","3,500",1.382,2.425,1.8,37
37,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (PARAQUAT = 61601)",300,1.01,1.978,2,4
38,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (PYRAFLUFEN-ETHYL = 30090)",None,None,None,None,None
39,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (SAFLUFENACIL = 118203)",None,None,None,None,None
40,2019,CALIFORNIA,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (TOTAL)","18,300",NaN,NaN,NaN,53
41,2019,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (BT KURSTAKI ABTS-351 =...",None,None,None,None,None
42,2019,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (CHLORANTRANILIPROLE = ...",None,None,None,None,None
43,2019,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (CRYOLITE = 75101)",None,None,None,None,None
44,2019,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (ESFENVALERATE = 109303)",None,None,None,None,None
45,2019,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (PYRIPROXYFEN = 129032)",100,0.103,0.121,1.2,17
46,2019,CALIFORNIA,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (TOTAL)","1,500",NaN,NaN,NaN,24
47,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (BT KURSTAKI SA-12 = 6518)",None,None,None,None,None
48,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (CYANAMID = 14002)","80,500",17.165,47.061,2.7,44
49,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (DICHLOROPROPENE = 29001)",None,None,None,None,None
50,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (FORCHLORFENURON = 128819)","1,400",0.356,0.829,2.3,45
51,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (MINERAL OIL = 63502)",None,None,None,None,None
52,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (STRYCHNINE = 76901)",None,None,None,None,None
53,2019,CALIFORNIA,"CHEMICAL, OTHER","CHEMICAL, OTHER: (TOTAL)","93,100",NaN,NaN,NaN,53

In [11]:
## Title case the "state" column
pesticide_kiwi["state"] = pesticide_kiwi["state"].str.title()
pesticide_kiwi.tail()

<ipython-input-11-c5ad7fd7f639>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pesticide_kiwi["state"] = pesticide_kiwi["state"].str.title()

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
49,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (DICHLOROPROPENE = 29001)",None,None,None,None,None
50,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (FORCHLORFENURON = 128819)","1,400",0.356,0.829,2.3,45
51,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (MINERAL OIL = 63502)",None,None,None,None,None
52,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (STRYCHNINE = 76901)",None,None,None,None,None
53,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (TOTAL)","93,100",NaN,NaN,NaN,53

In [12]:
## Drop blank rows
pesticide_kiwi = pesticide_kiwi.dropna()
pesticide_kiwi.tail()

,year,state,chemical_type,chemical_name,chem_app(lbs),lb/acre/app(avg),lb/acre/yr(avg),num_app(avg),pct_area_treated(avg)
36,2019,California,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (OXYFLUORFEN = 111601)","3,500",1.382,2.425,1.8,37
37,2019,California,"CHEMICAL, HERBICIDE","CHEMICAL, HERBICIDE: (PARAQUAT = 61601)",300,1.01,1.978,2,4
45,2019,California,"CHEMICAL, INSECTICIDE","CHEMICAL, INSECTICIDE: (PYRIPROXYFEN = 129032)",100,0.103,0.121,1.2,17
48,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (CYANAMID = 14002)","80,500",17.165,47.061,2.7,44
50,2019,California,"CHEMICAL, OTHER","CHEMICAL, OTHER: (FORCHLORFENURON = 128819)","1,400",0.356,0.829,2.3,45

In [13]:
## Reset the index
# pesticide_kiwi = pesticide_kiwi.reset_index(drop = True)
# pesticide_kiwi

In [14]:
pesticide_kiwi.to_csv("../pesticide_kiwi_19.csv",index=False)